package tel_ran.hsa.protocols.api;

public enum TcpRequest {
	ADD_WORKINGDAYS,
	REMOVE_WORKINGDAYS,
	GET_WORKINGDAYS,
	SET_WORKINGDAYS,
	
	ADD_DOCTOR,
	ADD_PATIENT,
	REMOVE_DOCTOR,
	REMOVE_PATIENT,
	UPDATE_DOCTOR,
	UPDATE_PATIENT,
	GET_DOCTOR,
	GET_PATIENT,
	ADD_HEALTHGROUP,
	REMOVE_HEALTHGROUP,
	SET_HEALTHGROUP,
	GET_HEALTHGROUP,
	SET_TIMESLOTS,
	SET_THERAPIST,
	
	GET_HEALTHGROUPS,
	GET_ALL_WORKINGDAYS,
	GET_DOCTORS,
	GET_PATIENTS,
	GET_VISITS,
	
	BUILD_SCHEDULE,
	BOOK_VISIT,
	CANCEL_VISIT,
	REPLACE_VISITS_DOCTOR,
	
	GET_PATIENT_DOCTORS,
	GET_DOCTOR_PATIENTS,
	
	GET_VISITS_BY_PATIENT,
	GET_VISITS_BY_DOCTOR,
	GET_FREE_VISITS,
	
	ADD_PULSE_INFO,
	GET_PULSE_BY_PERIOD, 
	GET_PULSE_INFO 

}
